version: 0.2.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: Chatbot/bin/Debug/Chatbot.exe
  name: Executable
deploy:
- provider: GitHub
  tag: 
  release: v$(appveyor_build_version)
  auth_token:
    secure: rnQb2k6w14URTv8ftGELTHwyiNY9qweCZkTLRtuXlEW3S/CQ+rVLmdmYbTAiPaND
  artifact: Executable
notifications:
- provider: Slack
  auth_token:
    secure: p5WKK0xPqN6jj3RrPuwpuxwLUP40mRx58dOfEzO46WVh+QVB+5VhduLOVlHoj7t8dyhEA0/gsxc8qHRnw+YxBQ==
  channel: ci
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true